// @ts-nocheck
import { browser } from 'fumadocs-mdx/runtime/browser';
import type * as Config from '../source.config';

const create = browser<typeof Config, import("fumadocs-mdx/runtime/types").InternalTypeConfig & {
  DocData: {
  }
}>();
const browserCollections = {
  docs: create.doc("docs", {"animated-gradient-button.mdx": () => import("../content/docs/animated-gradient-button.mdx?collection=docs"), "expand-button.mdx": () => import("../content/docs/expand-button.mdx?collection=docs"), "fold-button.mdx": () => import("../content/docs/fold-button.mdx?collection=docs"), "glass-button.mdx": () => import("../content/docs/glass-button.mdx?collection=docs"), "glow-button.mdx": () => import("../content/docs/glow-button.mdx?collection=docs"), "index.mdx": () => import("../content/docs/index.mdx?collection=docs"), "insta-button.mdx": () => import("../content/docs/insta-button.mdx?collection=docs"), "installation.mdx": () => import("../content/docs/installation.mdx?collection=docs"), "light-button.mdx": () => import("../content/docs/light-button.mdx?collection=docs"), "like-button.mdx": () => import("../content/docs/like-button.mdx?collection=docs"), "march-button.mdx": () => import("../content/docs/march-button.mdx?collection=docs"), "peel-button.mdx": () => import("../content/docs/peel-button.mdx?collection=docs"), "pluse-button.mdx": () => import("../content/docs/pluse-button.mdx?collection=docs"), "rainbow-button.mdx": () => import("../content/docs/rainbow-button.mdx?collection=docs"), "shadow-pop-button.mdx": () => import("../content/docs/shadow-pop-button.mdx?collection=docs"), "shimmer-button.mdx": () => import("../content/docs/shimmer-button.mdx?collection=docs"), "slant-button.mdx": () => import("../content/docs/slant-button.mdx?collection=docs"), "slide-icon-button.mdx": () => import("../content/docs/slide-icon-button.mdx?collection=docs"), "splash-button.mdx": () => import("../content/docs/splash-button.mdx?collection=docs"), "sweep-button.mdx": () => import("../content/docs/sweep-button.mdx?collection=docs"), "sweep-shimmer-button.mdx": () => import("../content/docs/sweep-shimmer-button.mdx?collection=docs"), "wave-button.mdx": () => import("../content/docs/wave-button.mdx?collection=docs"), }),
};
export default browserCollections;